Repository flywheel-io/core, pull requests merged in 2018-05, with the labels that each got.

#1186 Ensure that j_id is always a string
  api/handlers/containerhandler.py
  api/web/base.py
Labels: Bug

#1195 Add test and fix for set_file_classification calls
  sdk/codegen/src/main/java/io/flywheel/codegen/FlywheelCodegenSupport.java
  sdk/src/python/tests/integration_tests/test_acquisition.py
Labels: Bug, SDK

#1198 Formalize UserStorage and add ancillary cleanup
  api/dao/basecontainerstorage.py
  api/dao/containerstorage.py
  api/handlers/containerhandler.py
  api/handlers/listhandler.py
  api/handlers/userhandler.py
Labels: Enhancement

#1194 .raw doesn't work for boolean fields
  api/handlers/dataexplorerhandler.py
Labels: Bug

#1191 Pagination
  api/api.py
  api/auth/containerauth.py
  api/auth/groupauth.py
  api/auth/userauth.py
  api/dao/basecontainerstorage.py
  api/dao/containerstorage.py
  api/dao/dbutil.py
  api/handlers/collectionshandler.py
  api/handlers/containerhandler.py
  api/handlers/devicehandler.py
  api/handlers/grouphandler.py
  api/handlers/refererhandler.py
  api/handlers/userhandler.py
  api/jobs/batch.py
  api/jobs/gears.py
  api/jobs/handlers.py
  api/util.py
  api/web/base.py
  tests/integration_tests/python/conftest.py
  tests/integration_tests/python/test_pagination.py
Labels: Enhancement, Minor Change
