Repository flywheel-io/core, pull requests merged in 2018-11, with the labels that each got.

#1445 Generate parents for subjects created through uploads
  api/dao/hierarchy.py
  bin/database.py
  tests/integration_tests/python/test_upgrades.py
  tests/integration_tests/python/test_uploads.py
Labels: Bug, High Priority

#1455 Set parents on containers created via web upload
  api/placer.py
  tests/integration_tests/python/test_uploads.py
Labels: Bug, High Priority

#1453 Upgrade 60 to upgrade deleted sessions
  bin/database.py
  tests/integration_tests/python/test_upgrades.py
Labels: High Priority

#1460 Add row_number to data view columns
  api/data_views/column_aliases.json
  api/data_views/pipeline/read_file.py
  tests/integration_tests/python/test_data_views.py
Labels: Enhancement, Minor Change
