Repository flywheel-io/core, pull requests merged in 2018-08, with the labels that each got.

#1337 Use string for JobTicket lookup
  api/jobs/jobs.py
Labels: Bug

#1289 Add pagination to DataViews
  api/data_views/config.py
  api/data_views/data_view.py
  api/data_views/handlers.py
  api/data_views/pipeline/filter.py
  api/data_views/pipeline/skip_limit.py
  swagger/paths/data-views.yaml
  tests/integration_tests/python/test_data_views.py
Labels: Minor Change

#1345 Rename async keyword to async_
  sdk/codegen/src/main/resources/fw-python/api.mustache
  sdk/codegen/src/main/resources/fw-python/api_client.mustache
  sdk/codegen/src/main/resources/fw-python/flywheel.mustache
  sdk/docker/python3-test-env.sh
Labels: Minor Change, SDK

#1295 Support expressions on data-view columns
  api/data_views/column_aliases.json
  api/data_views/column_aliases.py
  api/data_views/config.py
  api/data_views/pipeline/extract_columns.py
  api/data_views/safe_eval.py
  swagger/schemas/definitions/data-view.json
  tests/integration_tests/python/test_data_views.py
  tests/unit_tests/python/test_safe_eval.py
Labels: Enhancement, Minor Change

#1346 Only check for major version differences by default
  sdk/codegen/src/main/resources/fw-python/flywheel.mustache
  sdk/codegen/src/main/resources/matlab/flywheel.mustache
Labels: Minor Change, SDK

#1313 Cli sdk login
  sdk/codegen/src/main/java/io/flywheel/codegen/MatlabGenerator.java
  sdk/codegen/src/main/resources/fw-python/__init__package.mustache
  sdk/codegen/src/main/resources/fw-python/flywheel.mustache
  sdk/codegen/src/main/resources/matlab/client.mustache
  sdk/src/matlab/sphinx/src/getting_started.rst
  sdk/src/python/sphinx/source/getting_started.rst
  sdk/src/python/tests/integration_tests/sdk_test_case.py
Labels: SDK

#1348 Add lookup function to getting started docs
  sdk/src/matlab/sphinx/src/getting_started.rst
  sdk/src/python/sphinx/source/getting_started.rst
Labels: SDK

#1303 Save data view results to container
  api/api.py
  api/create_file.py
  api/data_views/data_view.py
  api/data_views/handlers.py
  api/data_views/pipeline/report_progress.py
  api/files.py
  api/upload.py
  swagger/paths/data-views.yaml
  swagger/schemas/definitions/data-view.json
  swagger/schemas/input/save-data-view.json
  tests/integration_tests/python/test_data_views.py
Labels: Enhancement, Minor Change

#1352 Use 'invalid' keyword for disabled gears
  api/jobs/gears.py
  api/jobs/queue.py
  tests/integration_tests/python/test_gears.py
Labels: Bug

#1355 Analysis download as superuser doesn't 500
  api/download.py
  tests/integration_tests/python/test_analyses.py
Labels: Bug

#1354 Pluggable gear transport
  api/config.py
  api/jobs/gears.py
  api/jobs/jobs.py
  api/jobs/queue.py
Labels: Enhancement

#1365 Orange download
  api/download.py
  tests/integration_tests/python/test_download.py
Labels: Bug

#1368 Allow empty contents on upload
  sdk/codegen/src/main/resources/fw-python/file_spec.mustache
Labels: Bug, SDK

#1362 Custom gear UID/GID
  api/jobs/jobs.py
Labels: Enhancement

#1359 Batch Optional Inputs
  api/jobs/batch.py
  api/jobs/gears.py
  api/jobs/handlers.py
  swagger/schemas/definitions/batch.json
  swagger/schemas/input/propose-batch.json
  swagger/schemas/output/batch-proposal.json
  tests/integration_tests/python/test_batch.py
Labels: Breaking Change

#1369 Add Swagger documentation for api/jobs endpoint
  sdk/src/python/tests/integration_tests/test_job.py
  swagger/paths/jobs.yaml
  swagger/schemas/definitions/job.json
  swagger/schemas/output/all-jobs-list.json
Labels: Enhancement, Minor Change, SDK

#1380 Allow after_id to be blank, don't overwrite filter
  api/dao/dbutil.py
Labels: Enhancement, Minor Change

#1378 Add regex operator to pagination filter
  api/data_views/pipeline/filter.py
  api/util.py
  tests/integration_tests/python/test_data_views.py
  tests/integration_tests/python/test_pagination.py
Labels: Enhancement, Minor Change

#1386 SDK matlab fixes
  sdk/codegen/src/main/resources/matlab/model.mustache
  sdk/codegen/src/main/resources/matlab/model_base.mustache
  swagger/examples/output/job-config.json
  swagger/paths/jobs.yaml
  swagger/schemas/definitions/job.json
  swagger/schemas/output/job-config.json
Labels: Bug, SDK
