Repository flywheel-io/core, pull requests merged in 2018-07, with the labels that each got.

#1272 Add missing swagger docs
  swagger/paths/jobs.yaml
  swagger/paths/report.yaml
  swagger/schemas/definitions/job.json
  swagger/schemas/definitions/report.json
  swagger/schemas/input/job-completion.json
  swagger/schemas/output/job-completion-ticket.json
  swagger/schemas/output/report-access-log.json
  swagger/schemas/output/report-access-type-list.json
  swagger/schemas/output/report-usage.json
Labels: Tech Debt

#1279 Fix container ticketed download in matlab
  sdk/codegen/src/main/java/io/flywheel/codegen/FlywheelCodegenSupport.java
  sdk/src/matlab/testDrive.m
Labels: Bug

#1281 Add SDK test for get_config and fix schema problem
  sdk/src/python/tests/integration_tests/test_site_config.py
  swagger/schemas/definitions/config.json
Labels: SDK

#1282 Remove client-side validation from python SDK
  sdk/codegen/src/main/resources/fw-python/model.mustache
Labels: SDK

#1271 Add gear metadata to jobs and analyses
  api/dao/containerstorage.py
  api/jobs/gears.py
  api/jobs/jobs.py
  api/jobs/queue.py
  api/jobs/rules.py
  bin/database.py
  sdk/src/python/tests/integration_tests/test_analysis.py
  sdk/src/python/tests/integration_tests/test_job.py
  swagger/schemas/definitions/analysis.json
  swagger/schemas/definitions/gear.json
  swagger/schemas/definitions/job.json
  tests/integration_tests/python/test_analyses.py
  tests/integration_tests/python/test_jobs.py
  tests/integration_tests/python/test_upgrades.py
Labels: Tech Debt

#1189 Data views part 1
  .gitignore
  api/api.py
  api/config.py
  api/dao/containerstorage.py
  api/data_views/README.md
  api/data_views/__init__.py
  api/data_views/access_logger.py
  api/data_views/column_aliases.json
  api/data_views/column_aliases.py
  api/data_views/config.py
  api/data_views/data_view.py
  api/data_views/file_opener.py
  api/data_views/formatters.py
  api/data_views/handlers.py
  api/data_views/hierarchy_aggregator.py
  api/data_views/pipeline/__init__.py
  api/data_views/pipeline/aggregate.py
  api/data_views/pipeline/extract_columns.py
  api/data_views/pipeline/log_access.py
  api/data_views/pipeline/match_containers.py
  api/data_views/pipeline/missing_data_strategies.py
  api/data_views/pipeline/pipeline.py
  api/data_views/pipeline/read_file.py
  api/data_views/pipeline/write.py
  api/data_views/readers.py
  api/data_views/storage.py
  api/data_views/util.py
  sdk/src/python/sphinx/source/data_views.rst
  swagger/index.yaml
  swagger/paths/data-views.yaml
  swagger/schemas/definitions/data-view.json
  swagger/schemas/input/data-view-adhoc.json
  swagger/schemas/input/data-view-new.json
  swagger/schemas/input/data-view-update.json
  swagger/schemas/output/data-view-columns.json
  swagger/schemas/output/data-view-list.json
  swagger/schemas/output/data-view.json
  tests/integration_tests/python/test_data_views.py
Labels: Enhancement, Minor Change

#1182 Must have site admin to search all data
  api/handlers/dataexplorerhandler.py
  tests/unit_tests/python/conftest.py
  tests/unit_tests/python/test_dataexplorer.py
Labels: Breaking Change

#1287 Carry redundant node_type on resolver node
  api/resolver.py
  sdk/codegen/src/main/java/io/flywheel/codegen/MatlabGenerator.java
  sdk/codegen/src/main/resources/fw-python/model.mustache
  sdk/codegen/src/main/resources/matlab/model.mustache
  swagger/schemas/definitions/resolver.json
  tests/integration_tests/python/test_resolver.py
Labels: Minor Change

#1300 Doesn't assume job has gear-info
  api/dao/basecontainerstorage.py
Labels: Bug

#1299 Support filtering data-view files on gear name and version
  api/data_views/data_view.py
  api/data_views/file_opener.py
  api/data_views/pipeline/match_containers.py
  api/data_views/util.py
  swagger/schemas/definitions/data-view.json
  tests/integration_tests/python/test_data_views.py
Labels: Enhancement, Minor Change

#1293 Add datetime support to matlab client
  sdk/codegen/src/main/java/io/flywheel/codegen/MatlabGenerator.java
  sdk/codegen/src/main/resources/matlab/model.mustache
  sdk/codegen/src/main/resources/matlab/model_base.mustache
Labels: Enhancement, Minor Change

#1301 Properly handle long JSON property names in Matlab
  sdk/codegen/src/main/resources/matlab/model.mustache
Labels: Bug, SDK

#1302 Add sections on building and testing sdk
  sdk/README.md
Labels: Bug, SDK

#1305 Fix upgrade step to add gear_info to analyses
  bin/database.py
  tests/integration_tests/python/test_upgrades.py
Labels: Bug

#1308 Check for null before iterating fieldnames
  sdk/codegen/src/main/resources/matlab/model.mustache
Labels: SDK

#1320 Include response message in sdk exceptions
  sdk/codegen/src/main/resources/fw-python/rest.mustache
  sdk/codegen/src/main/resources/matlab/api_client.mustache
  sdk/src/python/tests/integration_tests/test_errors.py
Labels: SDK

#1321 Update launch spec for metrics mule
  docker/uwsgi-config.ini
Labels: Bug

#1328 Add collection to testDrive.m, fix collection issue
  sdk/codegen/src/main/resources/matlab/flywheel_methods.mustache
  sdk/src/matlab/testDrive.m
Labels: Bug, SDK
