Repository flywheel-io/core, pull requests merged in 2019-02, with the labels that each got.

#1517 [FLYW-348] Age should remain on session level, with DB Fix
  api/dao/hierarchy.py
  bin/database.py
  bin/fixes.py
  bin/process_cursor.py
  tests/integration_tests/python/test_upgrades.py
  tests/integration_tests/python/test_uploads.py
  tests/unit_tests/python/test_db_upgrade.py
Labels: Enhancement

#1525 Quick stats patch for exclusive tags
  api/jobs/queue.py
Labels: Bug

#1537 Add base class for core models
  api/models.py
  tests/unit_tests/python/test_base_model.py
Labels: Enhancement, Minor Change

#1515 [FLYW-126] Refactor download to use strategy pattern
  api/api.py
  api/data_export/__init__.py
  api/data_export/download_file_source.py
  api/data_export/file_filter.py
  api/data_export/handlers/__init__.py
  api/data_export/handlers/download_handler.py
  api/data_export/mappers/__init__.py
  api/data_export/mappers/download_tickets.py
  api/data_export/models/__init__.py
  api/data_export/models/download_target.py
  api/data_export/models/download_ticket.py
  api/data_export/strategy/__init__.py
  api/data_export/strategy/abstract.py
  api/data_export/strategy/bulk.py
  api/data_export/strategy/classic.py
  api/data_export/strategy/factory.py
  api/data_export/strategy/hierarchy.py
  api/data_export/tar_download_writer.py
  api/download.py
  api/handlers/refererhandler.py
  api/io/__init__.py
  api/io/response_writer.py
  api/io/url_file_wrapper.py
  api/models.py
  api/web/base.py
  sdk/src/python/tests/integration_tests/test_download_ticket.py
  tests/integration_tests/python/test_analyses.py
  tests/integration_tests/python/test_download.py
  tests/unit_tests/python/test_download.py
Labels: Enhancement, Minor Change

#1520 Add /jobs/ask
  api/api.py
  api/config.py
  api/handlers/containerhandler.py
  api/jobs/handlers.py
  api/jobs/jobs.py
  api/jobs/queue.py
  swagger/paths/jobs.yaml
  swagger/schemas/definitions/job.json
  swagger/schemas/input/job-ask.json
  tests/integration_tests/python/test_jobs.py
  tests/requirements.txt
  tests/unit_tests/python/test_queue.py
  tests/unit_tests/python/test_validators.py
Labels: Enhancement

#1526 [FLYW-368] Add build-your-own tree endpoint
  api/api.py
  api/container/__init__.py
  api/container/graph.py
  api/container/handlers/__init__.py
  api/container/handlers/tree_handler.py
  api/container/tree_retrieval.py
  api/dao/basecontainerstorage.py
  swagger/index.yaml
  swagger/paths/tree.yaml
  swagger/schemas/definitions/tree.json
  swagger/schemas/input/tree-request.json
  swagger/schemas/output/graph-response.json
  swagger/schemas/output/tree-response.json
  tests/integration_tests/python/test_tree.py
Labels: Enhancement, Minor Change
