Repository flywheel-io/core, pull requests merged in 2019-01, with the labels that each got.

#1470 [FLYW-50] Convert template to templates
  api/dao/containerstorage.py
  api/dao/hierarchy.py
  api/handlers/containerhandler.py
  bin/database.py
  swagger/examples/input/project-template.json
  swagger/schemas/definitions/project-template.json
  swagger/schemas/definitions/project.json
  tests/integration_tests/python/test_containers.py
  tests/integration_tests/python/test_upgrades.py
Labels: Breaking Change

#1493 Set concurrency type for coverage
  api/web/start.py
Labels: Minor Change

#1492 Add detail endpoint for jobs.
  api/api.py
  api/dao/containerutil.py
  api/jobs/handlers.py
  swagger/paths/jobs.yaml
  swagger/schemas/definitions/job.json
  swagger/schemas/output/job-detail.json
  tests/integration_tests/python/test_jobs.py
Labels: Enhancement, Minor Change

#1505 Add --py3lint option to tests.sh
  tests/.py3lintrc
  tests/bin/tests.sh
Labels: Low Hanging Fruit, Tech Debt

#1487 Add indexes for commonly used queries
  api/config.py
  tests/integration_tests/python/test_uploads.py
Labels: Enhancement, Minor Change, Performance
